[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name              tail
    Path              /var/log/suricata/eve.json
    Parser            json
    Tag               suricata.eve
    Refresh_Interval  5
    Skip_Long_Lines   On
    DB                /tmp/flb_suricata.db

[FILTER]
    Name   record_modifier
    Match  suricata.eve
    Record source project-radiant-suricata

[OUTPUT]
    Name            es
    Match           suricata.eve
    Host            elasticsearch
    Port            9200
    Index           suricata-eve
    Suppress_Type_Name On
    Generate_ID     On